
<%@ page language="java" contentType="text/html; charset=UTF-8"	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<c:url var="ROOT" value="/"></c:url>
<c:url var="RESOURCES" value="/resources/"></c:url>

<script type="text/javascript">
	var contextRoot = "${ROOT}";
	var parentApi = "api";
	var api = {
		LOGIN_URL:+"/login/",
		EMAIL_VALIDATE_ADDOWNER:parentApi+"/device/owner/",
		DEVICEOWNER_VALIDATE:parentApi+"/device/owner/validate/",
		DEVICEOWNER_DEL:parentApi+"/device/owner/delete/",
		CHECK_DEV_LABEL:parentApi+"/device/bylabel/",
		CHECK_DEV_NUMBER:parentApi+"/device/bynumber/",
		GETCITYBY_ID:parentApi+"/city/",
		GETCATEGORYBY_ID:parentApi+"/category/",
		GETCATEGORY_LIST:parentApi+"/categoryList",
		GETPHOTOIDBY_ID:parentApi+"/photoId/",
		GETPHOTOID_LIST:parentApi+"/photoIdList",
		DEVICE_BY_ID:parentApi+"/device/byId/",
		DEVICES_BY_MAKE:parentApi+"/devices/byMake/",
		DEVICE_OWNERNAME_EMAIL_VALIDATE : parentApi+ "/device/ownername/email/validate/",
		DEVICE_NUMBER_VALIDATE : parentApi+ "/device/phoneNumber/validate/",
        PURCHASEORDER_LIST:parentApi+"/purchaseOrderDropDown",
		ISSUE_TYPE_LIST:parentApi+"/issue/team/",
		ISSUE_TYPE_ADD:parentApi+"/issue/save",
        ITEM_LIST_BYID:contextRoot+parentApi+"/items/byId",
        
        TIP_SAVE:parentApi+"/tipstricks/save",
		TIPS_LIST:parentApi+"/tipstricks/issue/",

		GET_TEAMS_LIST:parentApi+"/team/list",
		GET_ISSUES_BY_TEAMID:parentApi+"/issue/team/",

		ACCESSORY_SAVE:parentApi+"/accessory/save",
		ACCESSORY_LIST_BYTEAM:parentApi+"/accessory/team/",
		ACCESSORY_BYID:parentApi+"/accessory/byid/",
		ACCESSORY_LIST:parentApi+"/accessory/list",
		

		UNASSIGNED_HARDWARE:parentApi+"/device/unassigned/",
		UNASSIGNED_DEVICE_LIST:parentApi+"/device/unassigned/device/",
		
		LOCATION_LOOKUP:parentApi+"/location/random?number=",
		DEVICE_MAKE:parentApi+"/device/make",
		CHECK_DEV_MAKE:parentApi+"/device/makename/",
		CHECK_DEV_MODEL:parentApi+"/device/modelname/",
		SAVE_MAKE:parentApi+"/make/save",
		SAVE_MODEL:parentApi+"/model/save",
		DEVICE_MODEL:parentApi+"/device/model/",
		ORGANIZATION_SAVE:parentApi+"/organization/save/",
		ORG_BY_ID:parentApi+"/org/byid/",
		NO_HARDWARE_OWNERS:parentApi+"/device/owners/no-hrdware/",
		ASSIGN_OWNER:parentApi+"/devices/assign/owner/",
		UNASSIGN_OWNER:parentApi+"/devices/unassign/owner",
		ANALYZE_AUTO_ASSIGN:parentApi+"/device/list/autoassign/",
		DO_AUTOASSIGN:parentApi+"/devices/analyse-assign/",
		
		ORGANIZATION_LIST:parentApi+"/organization/list/",
		DIV_OWNER_SAVE:parentApi+"/divisionOwner/save/",
		OWNER_LIST:parentApi+"/divisionOwner/list/",
		DEVICEOWNER_SAVE:parentApi+"/device/owner/save/",
		DEVICEOWNER_EDIT_UPDATE:parentApi+"/device/owner/edit/",
		DEVICEOWNER_LIST:parentApi+"/device/owner/list/",
		DEVICEOWNERS_WITH_HARDWARE_LIST:parentApi+"/device/owners/list/",
		DEVICEOWNER_OBJECT:parentApi+"/device/owner/",
		DEVICE_LIST:parentApi+"/device/listbyorg/", //Device list by org
		NEW_DEVICE_SAVE:parentApi+"/newDevice/save",
		DEVICES_ALL:parentApi+"/device/list",
		DEVICE_EDIT_UPDATE:parentApi+"/device/update",
		COMPANIES_LIST:parentApi+"/companies/list",
		
		DEVICE_HISTORY:parentApi+"/device/history/",
		DEVICEOWNER_BY_ID:parentApi+"/owner/by/",
		GET_DEV_MAKE :parentApi+"/make/",
		GET_DEV_MODEL :parentApi+"/model/",
		
		INVENTORY_SAVE:parentApi+"/inventory/save",
		INVENTORY_LIST_BY_ORGID:parentApi+"/inventory/list/",
		
		DEVIVE_BULKUPLOAD:parentApi+"/device/upload/",
		COMPANIES_SAVE:parentApi+"/companies/save",
		PARTNERS_SAVE:parentApi+"/partners/save",
		PARTNERS_LIST:parentApi+"/partners/list",
		
	//device software
		//device software->deployment dashaboard
		 SEND_APPDEPLOYMENT_EMAILS:parentApi+"/app-deployment/email", 
		 SEND_APPDEPLOYMENT_SMS:parentApi+"/app-deployment/sms",
		
		 //device software->App configuration
		 SAVE_APP_CONFIG_SETTINGS:parentApi+"/config-setting/save/",
		
		 //account setup
		ACCSETUPCONTACTS_SAVE:parentApi+"/accountsetup/contacts/save",
		ACCSETUPCONTACTS_LIST:parentApi+"/accountsetup/contacts/list/",
		ACCSETUPEXISTINGCONTACTS_LIST:parentApi+"/accountsetup/existingcontacts/list/",
		TASKASSIGN_SAVE:parentApi+"/taskassign/save",
		PROCUREMENT_SAVE:parentApi+"/procurement/save",
		PROC_STD_SAVE:parentApi+"/prostandard/save",
		PROC_STD_LIST:parentApi+"/prostandard/list/",		
		GENERAL_SAVE:parentApi+"/general/save/",
		GENERAL_LIST:parentApi+"/general/list/",
		SHIPPING_ACCOUTNS_SAVE:parentApi+"/shpng-accounts/save/",
		MDM_CONFIGURATION:parentApi+"/mdm/configure/",
		EXCHANGE_ACCNTS:parentApi+"/exchng-acc/save/", 
		BILLING_INFO_SAVE:parentApi+"/bill-info/save/",
		BILLING_INFO_LIST:parentApi+"/bill-info/list/",
		DELETE_CONTACTS : parentApi+"/delete/contacts/",

		
		
		CUSTOMERNOTES_SAVE:parentApi+"/customerNotes/save",
		ACCOUNT_BULKUPLOAD:parentApi+"/account/upload",
		DEVICE_OWNER_BULKUPLOAD:parentApi+"/devOwner/upload/",
		ENABLEDDEVICE_COUNT:parentApi+"/enabledDevice/",
		TICKET_SAVE:parentApi+"/ticket/save",
		TICKET_TYP_LIST:parentApi+"/ticket/type/all",
		SAVEDEVICE_NOTES:parentApi+"/deviceNotes/save",
		CHECK_DUPLICATE_LOGIN_CEMAIL:parentApi+"/checkduplicate/Logincontactemail/",
		
		//Ticketing URL's
		GET_ALL_TICKET			:	parentApi + "/ticket/get",
		CREATE_TICKET:parentApi+"/ticket/new",
		DELETE_TICKET:parentApi+"/ticket/delete/",
		TICKET_BY_DEVICEID:parentApi+"/get/ticketBy/",
		
		// Tickets Comments URL
		GET_ALL_TICKET_BY_ID	:	parentApi + "/ticket/comments/get",
		POST_COMMENT_OF_TICKET	:	parentApi + "/ticket/comments/post",
		SEARCH_TICKET_LIST		:	parentApi+"/searched/ticket",
		GET_EMAIL_FOR_TICKET	:	parentApi + "/ticket/get/thread",
		SEND_EMAIL_REPLAY		:	parentApi + "/ticket/replay/to",
		SALES_LIST              :   parentApi + "/ticket/get/thread",
		SALES_LIST_ALL          :   parentApi + "/ticket/get/thread/all",
		TICKET_PROCURE          :	parentApi + "/ticket/update/procurement",
		TICKET_REASSIGN         :   parentApi +"/ticket/reassign",
		TICKET_TRANSFER       :   parentApi +"/ticket/transfer",
		
		TICKET_PROCURE_TRANSIT  :   parentApi + "/ticket/update/procurement/transit/",
		TICKET_PROCURE_CLOSE  :   parentApi + "/ticket/update/procurement/close/",
		TICKET_SUBMIT_FEEDBACK  :   parentApi + "/ticket/feedbackSubmit",
		
		//Employee Left 
		TICKET_CLOSE_EMPLOYEE_LEFT  : parentApi + "/ticket/EmployeeLeft/close",
		
		TICKET_DELETE_REQUEST	:	parentApi + "/ticket/delete/emailrequest/",
		TICKET_BY_TKTNO			:	parentApi + "/ticket/byticketno/",
		
		LOCATION_SAVE           :   parentApi + "/location/save",
		LOCATION_LIST           :   parentApi + "/location/list/",
		LOCATION_DEL			:    parentApi + "/shipinLocation/delete/",
		GET_ACTIVITY_BY_TICKET	: 	parentApi + "/ticket/get/activity/",
		GET_ACTIVITY_BY_TICKETNO	: 	parentApi + "/ticket/activity/",
		SAVE_GLCODE             :   parentApi + "/save/glcode",
		GLCODE_LIST             :   parentApi + "/glcode/list/",
		SUBACCOUNT_LIST         :   parentApi + "/subAccount/list/",
		SAVE_SUBACCOUNT         :   parentApi + "/save/subaccount/",
		DELETE_GLCODE           :   parentApi + "/delete/glcode/",
		DELETE_SUBACCOUNT       :   parentApi + "/delete/subAccount/",
		EXE_CARE_RATE_SAVE      :   parentApi + "/execarerate/save",
		EXE_CARE_RATE_LIST      :   parentApi + "/execarerate/list",
		ASSIGNED_OWNER_TO_DEVICE:   parentApi + "/assigned/device",
		EXE_CARE_PLAN_SAVE      :   parentApi + "/execareplan/save",
		GET_DETAIL_FOR_FUNNEL   :   parentApi + "/ticket-details-for-funnel/",
		RATE_MODEL_LIST         :   parentApi + "/rate-model-list/",
		NEW_CLAIM_SAVE          :   parentApi + "/claim/save",
		CLAIM_LIST         		:   parentApi + "/claim/list",
		COUNTRY_LIST            :   parentApi + "/country/list",
		GET_TICKET_BY_STAGES    :   parentApi + "/ticket/list/by/status/",
		NEW_DEV_APPROVE    		:   parentApi + "/ticket/newDevice/approve",
		NEW_DEV_PROCURE    		:   parentApi + "/ticket/newDevice/procure",
		NEW_DEV_CLOSE    		:   parentApi + "/ticket/newDevice/close",
		CLEAR_COST_CARRIER     :   parentApi + "/clear-cost/carrier/",
		CLEAR_COST_CARRIER_VALIDATE : parentApi+"/clear-cost/carrier/validate/",
		CLEAR_COST_CARRIER_VALIDATE_EDIT :parentApi+"/clear-cost/carrier/validate/",
		GLCODE_VALIDATE : parentApi+"/glCode/validate/",
		SUBACCOUNT_VALIDATE : parentApi+"/subAccount/validate/",
		GET_CARRIER_BY_ID: parentApi+"/carrier/byid/",
		
		//invoice analysis
		SAVEINVOICE             : parentApi + "/invoice/save/" ,
		DELETE_INVOICE          : parentApi + "/invoice/delete/" ,
		UPLOAD_INVOICE          : parentApi + "/invoice/upload" ,
		LISTCARRIER				: parentApi + "/carrier/list",
		LIST_FILE_TYPES         : parentApi + "/invoice/file-types",
		LIST_INVC_BY_ORG        : parentApi + "/invoices/byorg/",
		INVCE_ClEAR_COST        : parentApi + "/invoiceFor/totalCostChart/byOrgId/",
		INVCE_BY_ID				: parentApi	+ "/invoice/byid/",
		INVC_ANALYSIS_DATA		: parentApi + "/analysis/data/",
		COPY_POLICY_LIST        : parentApi + "/copy-policy-list",
		POLICY_GROUP_LIST       : parentApi + "/policy-group-list/",
		SAVE_POLICY_GROUP       : parentApi + "/save-policy-group",
		SAVE_POLICY_NAME        : parentApi + "/save-policy-name",
		LIST_FOR_LINE_CHART     : parentApi + "/list-for-line-chart/",
		LIST_FOR_UNUSED_LINE_CHART : parentApi + "/list-for/UnUsed-line-chart/",
		BELL_DETAIL_LIST        : parentApi + "/bell-mob-list",

		AVG_COST_BY_CARRIER : parentApi + "/avg/cost-by-carrier/",
		TOP_COST_DEVICES : 		parentApi + "/top-cost-devices/",
		COST_BY_HRDWARE : 		parentApi + "/cost-by-hardware/",
		GET_DATA_BY_EACH_CARRIER : parentApi + "/get-data/by-each-carrier/",
		GET_DATA_FOR_COST_BY_HARDWARE : parentApi + "/data-for/cost-by-hrdwre-chart/",
		TOTAL_COST_CHART_BY_CARRIER   : parentApi + "/get/total-cost-chart-data/by-carrier/",
		TOTAL_COST_CHART_BY_INVOICE  : parentApi + "/avg/cost-by-invoice/",
		TOTAL_COST_CHART_BY_DIVISION  : parentApi +"/avg/cost-by-division/",
		//User API
		USER_SAVE : parentApi + "/user/add",
		USER_ROLE : parentApi + "/user/roles",
		USER_LIST :  parentApi + "/user/list",
		ROLE_SAVE : parentApi + "/role/add",
		SAVE_TRBLE_ISSUE_HIGH_PRIORITY:  parentApi + "/save/trble-issue/high-priority",
		SAVE_ROAMING_PACKAGES : parentApi + "/save/roaming-packages",
		SUMMARY_REPORTS : parentApi + "/summary-reports",
		
		//inventory location
		INV_LOCATION_SAVE : parentApi + "/invlocation/save/",
		INV_LOCATION_LIST : parentApi + "/invlocation/list/",
		SAVE_ACCSSRY_IN_DVC_TKT: parentApi + "/save-accessory/for-device-tkt-type",
		//line state of view and edit device
		UPDATE_LINE_STATE : parentApi + "/update-line-state",
		SAVE_ACCESSORY_FOR_RPLMNT_DVC : parentApi + "/save-replmnt-device-accessory",
		ACCESSORY_LIST_FOR_RPLMNT_DVC : parentApi + "/list-of-accessory/for-replmnt-device/",
		SAVE_RPLMNT_DEV_APPROVE : parentApi + "/replcDev/approve",
		DEALER_LIST             : parentApi + "/dealers/list/",
		SEND_MAIL_DEALER        : parentApi + "/sent-mail/to-dealer",
		//sub account list for mapping
		SUBACCOUNT_LIST_FOR_MAPP: parentApi + "/list/subAccountForMapping/",
		SAVE_GLCODE_SUBACC_MAPPING : parentApi + "/save/glcodeSubAccMapping",
		UNASSIGNED_DIVISION_LIST   : parentApi + "/unassigned-division-list/",
		BILLING_PERIOD			: parentApi + "/billing/period/",
		MAPPED_UNASSGN_GLSUBCODE   :  parentApi + "/mapping/unassign-gl-subAcc-code",
		SAVE_CLR_COST_CARRIER      :  parentApi + "/save/clear-cost/carrier",
		CLR_COST_CARRIER_LIST      :  parentApi + "/clear-cost/carrier/list/",

		INVC_BY_BILLPERIOD : parentApi + "/invoices/billing-period/",
		PARTY_LIST : parentApi+ "/partyListDropdown",
		SALES_LIST_BY_SOID: contextRoot+parentApi + "/sales-order/",
		SALES_ITEM_BY_SALESITEMID:contextRoot+parentApi + "/sales-Item/",
		SAVE_PURCHASE_ORDER:parentApi + "/save/purchaseOrder",
		PURCHASE_LIST_BY_POID: parentApi + "/getPurchaseItemList",
		DELETE_ITEM:parentApi+"/item/delete/",
		ADD_STOCK : parentApi+"/add/stock",
		STOCK_LIST:parentApi+"/stock/list",
		UNITS_LIST:parentApi+"/units/list",
		ADD_SUPPLIER:parentApi+"/add/supplier",
		SUPPLIER_LIST:parentApi+"/supplier/list",
		PREFERRED_SUPPLIER_LIST:parentApi+"/supplier_preferred/list",
		VALIDATE_SUPPLIER_EXIST:parentApi+"/supplier/validate",
		VALIDATE_CLIENT:parentApi+"/client/validate",
		CONTACT_BY_PARTY : parentApi+"/party-contact",
		CATEGORY_LIST:parentApi+"/list/category",
		ADD_CATEGORY:parentApi+"/add/category",
		SAVE_PARTY_CATEGORY:parentApi+"/save/Party_category",
		PARTY_CATEGORY_BY_PARTYID:parentApi+"/party_category/partyId",
		CITY_LIST:parentApi+"/city-list/",
		DELETE_PURCHASE_ITEM:contextRoot+parentApi+"/purchase/delete",
		PO_ADDRESSES:contextRoot+parentApi+"/po/address/",
		PO_PURCHASECOPY:contextRoot+parentApi+"/po/purchaseCopy/",
		DELETE_PARTY_ALT_ADDRESS:parentApi+"/partyAltAddress/delete",
		DELETE_CATEGORY:parentApi+"/category/delete",
		VALIDATE_CATEGORY:parentApi+"/category/validate",
		DELETE_PARTY_BANK_DETAILS:parentApi+"/partyBank/delete",
		STOCK_HISTORY_BYID:parentApi+"/stock/history",
		TYPE_LIST:parentApi +"/type/list",
		ADD_TYPE:parentApi+"/type/add",
		DELETE_TYPE:parentApi+"/type/delete",
		VALIDATE_TYPE:parentApi+"/type/validate/",
		STATE_LIST:parentApi+"/state/list",
		STATE_BY_ID:parentApi+"/state/byId",
		SAVE_CITY:parentApi+"/city/add",
		SAVE_DESIGNATION:contextRoot+parentApi+"/add/designation",
		DESIGNATION_LIST:parentApi+"/designation/list",
		DELETE_DESIGNATION:parentApi+"/designation/delete",
		DESIGNATION_VALIDATE:parentApi+"/designation/validate",
		DELETE_CITY:parentApi+"/city/delete",
        CITY_VALIDATE:parentApi+"/city/validate",
		COUNTRY_LIST:parentApi+"/country/list",
		SAVE_STATE:parentApi+"/state/add",
		GET_PURCHASE_ITEMS_BYID:parentApi+"/purchase-item_byId",
		GET_GRN_ITEMLIST_BYGRNID:parentApi+"/grn_items_by_grnId/",
		GET_GRN_ITEMLIST_BYPONO:parentApi+"/grn_items_by_poNo/",
		GET_PARTY_ADDRESS_LIST:parentApi+"/partyAddress/list",
		GET_PARTY_ADDRESS_BY_PARTYID:parentApi+"/partyAddress/list_by_partyId",
		GET_SO_ADDRESS:parentApi+"/so_address/terms_and_condition",
		GET_PARY_ADDRESS_BYADDRESSID:parentApi+"/party_address/by_id",
		GET_SALESORDERLIST_BYPARTYID:parentApi+"/sales_order_list/by_party_id",
		GET_DCLIST_BYSOID:parentApi+"/dcList/by_so_id",
		GET_SALESORDER_BYID:parentApi+"/sales_order/by_id",
		GET_DC_ITEMLIST_BYDCID:parentApi+"/dcItemList/by_dc_id",
		GET_INVOICEITEMLIST_BY_INVOICEID:parentApi+"/invoiceItemList/by_invoice_id",
		GET_DCITEM_BYDCITEMID:parentApi+"/dc-item",
		ADD_SO_DESIGN:parentApi+"/add/design",
		SO_DESIGNITEM_LIST:parentApi+"/design_item_list/by_sales_item_id",
		DELETE_DESIGN:parentApi+"/design/delete",
		DESIGN_VALIDATE:parentApi+"/design/validate",
		DESIGNITEMS_BY_SALESITEMID:contextRoot+parentApi+"/designList/salesItemId",
		DELETE_SALESITEM:parentApi+"/salesItem/delete",
		DESIGN_LIST:contextRoot+parentApi+"/design_list/by_sales_item_id",
		SALES_LIST_WITH_STATUS_NOT_CLOSED:parentApi+"/sales_list/with_status_not_closed",
		SALES_LIST_PENDING:parentApi+"/sales_list/pending",
		PURCHASE_LIST:parentApi+"/purchase_List",
		PURCHASE_LIST_PENDING:parentApi+"/purchase_List/pending",
		INVOICE_LIST:parentApi+"/invoice_List",
		GET_ALL_SALES_LIST:parentApi+"/get_all_sales_list",
		UPLOAD:parentApi+"/upload",
		STOCK_LIST_BY_ITEMID:parentApi+"/stock-list/by_itemId",
		STOCK_LIST_BY_ITEMID_AND_CLIENTID:parentApi+"/stock-list/by_itemId_clientId",
		DC_EXIST:parentApi+"/check_dc_exists",
		GET_DCITEMLISTByAllDC_BYSOID:parentApi+"/dc_itemlist_for_all_dc/by_soId",

		GET_SALES_ITEMS_WITHOUT_DESIGN:parentApi+"/sales-items-without-design",

		GET_POITEMSINPO:parentApi+"/purchase/items/list",
		POITEM_LASTPRICE:contextRoot+parentApi+"/poItem/LastPrice",
		GET_DCITEMLISTBYAllDC:parentApi+"/dc_itemlist_for_all_dc",
		STOCK_BYITEMID:contextRoot+parentApi+"/stock/list/ItemId",
		CHECK_DC_INVOICE_EXIST:contextRoot+parentApi+"/check_dc_invoice_exists",
		GET_ITEM_LIST:parentApi+"/get/item_list",
		UPDATE_PAYMENT_STATUS:parentApi+"/payment_status",
		GET_PO_BY_PONUMBER:parentApi+"/get_po_by_ponumber",
		GET_POLIST_BY_ITEMID:parentApi+"/purchase_list/by_item_id",
		GET_PURCHASEITEM_BY_ITEMID_SALESITEMID:contextRoot+parentApi+"/purchase_item_by_item_id",
		GET_SALES_ITEM_BY_ID:parentApi+"/sales-Item_by_id",
		GET_WORK_ORDER_ITEM_LIST_BY_WO_ID:parentApi+"/workOrderItemList/by_wo_id",
		GET_TDS_APPROVED_LIST:parentApi+"/tds_approved_list",
		GET_SALES_ITEMS_LIST_WITHOUT_DESIGN:parentApi+"/salesItems_without_design_list",
		GET_ITEMS:parentApi+"/get_all_itemList",
		NON_BILLABLE_ITEMS_BY_ID:parentApi+"/non_billable_items_by_id",
		SALES_LIST_PENDING_PARTIAL:parentApi+"/sales_list/pending_partial",
		PURCHASE_LIST_PENDING_PARTIAL:parentApi+"/purchase_List/pending_partial",
		INVOICE_LIST_PARTIAL:parentApi+"/invoice_List_partial",
		GET_PARTIAL_SALES_LIST:parentApi+"/get_all_sales_list_partial",
		GET_TDS_APPROVED_LIST_PARTIAL:parentApi+"/tds_approved_list_partial",
		GET_SALES_ITEM_WITHOUT_DESIGN_PARTIAL:parentApi+"/salesItems_without_design_list_partial",
		GET_SALES_ITEMS_LIST_BY_SALES_ORDER_ID:parentApi+"/salesitem_list_by_id",
		UPDATE_SO_ARCHIVE:contextRoot+parentApi+"/update_so_archive",
		UPDATE_SO_UNARCHIVE:contextRoot+parentApi+"/update_so_unarchive",
		UPDATE_PO_ARCHIVE:contextRoot+parentApi+"/update_po_archive",
		UPDATE_PO_UNARCHIVE:contextRoot+parentApi+"/update_po_unarchive",
		UPDATE_DC_ARCHIVE:contextRoot+parentApi+"/update_dc_archive",
		UPDATE_DC_UNARCHIVE:contextRoot+parentApi+"/update_dc_unarchive",
		UPDATE_GRN_ARCHIVE:contextRoot+parentApi+"/update_grn_archive",
		UPDATE_GRN_UNARCHIVE:contextRoot+parentApi+"/update_grn_unarchive",
		SO_MOTNHLY_REPORT:parentApi+"/so_monthly_chart",
		MAKE_LIST:parentApi +"/make/list",
		ADD_MAKE:parentApi+"/make/add",
		DELETE_MAKE:parentApi+"/make/delete",
		VALIDATE_MAKE:parentApi+"/make/validate/",
		GET_PARTIAL_DC_ITEMS:parentApi+"/partial_dc_items",
		FILE_UPLOAD:parentApi+"/clientPo/upload",
		FILE_DOWNLOAD:parentApi+"/clientPo/download",
		SO_LIST_BY_CLIENTID:parentApi+"/get_solist_byclient",
		SALES_UPLOAD:parentApi+"/sales/upload",
		SALES_LIST_BY_SOID_AND_VENDORID:contextRoot+parentApi+"/sales_item_list_by_soId/",
		SUPPLIER_LIST_WITH_PO_HISTORY:parentApi+"/supplier/list/with_purchase_history",
		MODEL_QTY_DETAILS:contextRoot+parentApi+"/model/qty_details",
		USER_LIST:parentApi+"/get_user_list",
		ITEMS_UPLOAD:parentApi+"/items/upload",
		DC_LIST:parentApi+"/dc_list",
		PURCHASE_UPLOAD:parentApi+"/purchase/upload",
		SALES_ARCHIVE:parentApi+"/sales/archive",
		GET_SALES_LIST_WITH_DESIGN:parentApi+"/salesOrder_with_design_withou_po_list",
		GET_SALES_ITEM_WITH_DESIGN_PARTIAL:parentApi+"/salesItems_with_design_list_partial",
		GET_SALES_ITEM_WITH_DESIGN_AND_PO_NOT_DONE_LIST_BY_SOID:parentApi+"/get_salesItem_list_by_id",
		DESIGN_UPLOAD:parentApi+"/design/upload",
		STOCK_QTY_DETAILS:parentApi+"/stock/qty_details",
		SO_DESIGNITEM_LIST_BY_SOITEMID:parentApi+"/designItem_list/sales_item_id",
		EMPLOYEE_LIST:parentApi+"/employee_list"
		
		
		
		

		
		
	}

	// Method for Get absolute Url
	function getUrl(name) {
		return contextRoot + name;
	}

</script>